name: Main pipeline

on: [push, pull_request]

jobs:
  static-analysis:
    runs-on: [ubuntu-latest]
    steps:

      - uses: actions/checkout@v2
      - name: Run ShellCheck
        run: |
          shellcheck scripts/*.sh

      - name: Run gofmt
        run: |
          ./scripts/checks.sh
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Get Image dependencies
        run: |
          docker pull golang:latest

      # there are some tests where we explicitly don't want to create an
      # image in code itself, so we have an image ready-to-go here
      - name: Build test images
        run: |
          docker build -f testresources/echoserver.Dockerfile -t echoserver:latest ./testresources

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          go get gotest.tools/gotestsum

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: gotestsum
        run: gotestsum --format short-verbose ./...
