name: Main pipeline

on: [push, pull_request]

jobs:
  static-analysis:
    runs-on: [ubuntu-latest]
    steps:

      - uses: actions/checkout@v2
      - name: Run ShellCheck
        run: |
          shellcheck scripts/*.sh

      - name: Run gofmt
        run: |
          ./scripts/checks.sh
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: does this build on windows?
        if: ${{ matrix.platform == 'windows-latest' }}
        run: docker build -f .\testresources\echoserver.Dockerfile .

      - name: test it
        run: go test -v -run=TestContainerAttachedToNewNetwork ./...
