name: Main pipeline

on: [push, pull_request]

jobs:
  static-analysis:
    runs-on: [ubuntu-latest]
    steps:

      - uses: actions/checkout@v2
      - name: Run ShellCheck
        run: |
          shellcheck scripts/*.sh

      - name: Run gofmt
        run: |
          ./scripts/checks.sh
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, 1.x]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          go get gotest.tools/gotestsum

      - name: modVerify
        run: go mod verify

      - name: modTidy
        run: go mod tidy

      - name: vet
        run: go vet ./...

      - name: compile
        run: |
          echo "building/compiling for operating system: $GOOS ..."
          go build

      - name: gotestsum
        # don't run tests unless we are on linux
        # there are a few considerations we need to account
        # for like installing docker on the mac platform and
        # using a network mode other than bridge for windows
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: gotestsum --format short-verbose ./...
