name: Main pipeline

on: [push, pull_request]

jobs:
  static-analysis:
    runs-on: [ubuntu-latest]
    steps:

      - uses: actions/checkout@v2
      - name: Run ShellCheck
        run: |
          shellcheck scripts/*.sh

      - name: Run gofmt
        run: |
          ./scripts/checks.sh
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Does docker work?
        uses: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock docker:latest version

      - name: test it
        run: go test -v -run=TestContainerCreationWithName ./...
